### ISSUE TITLE
Add button in the about me section that takes to a page containing the CV

### ISSUE THREAD

**Issue by thalytabdn** [thalytabdn/Portfolio#1]

**Comment by nizz009** [comment]
Hello! I would love to work on this project. Can I be assigned to contribute to this?

**Comment by thalytabdn** [comment]
of course, feel free :)

**Comment by ankitminglani** [comment]
@thalytabdn First time participating in hacktober fest. Please accept my contribution.
This is fine project, we should build the resume page as well. could be used by many to showcase their projects

**Comment by thalytabdn** [comment]
it's a good idea, but I prefer to use this button to take to the pdf file of the curriculum

**Comment by thalytabdn** [comment]
> @thalytabdn First time participating in hacktober fest. Please accept my contribution.
> This is fine project, we should build the resume page as well. could be used by many to showcase their projects

**Comment by thalytabdn** [comment]
> @thalytabdn First time participating in hacktober fest. Please accept my contribution.
> This is fine project, we should build the resume page as well. could be used by many to showcase their projects

it's a good idea, but I prefer to use this button to take to a pdf file of the curriculum, where it can be downloaded.

**Comment by ankitminglani** [comment]
should we point it to any random pdf for now to showcase on this repo ?

**Comment by thalytabdn** [comment]
Yes, can you do it ?

**Comment by ankitminglani** [comment]
Yes, its easy. I am thinking i will put a dummy resume pdf in the repo so
we show it on the button click in a new window. Does that sounds good ?

would you be comfortable to assign me this issue ?

**Comment by ankitminglani** [comment]
@thalytabdn Added the PDF part, please check. 
Regards

**Comment by ankitminglani** [comment]
@thalytabdn thanks for the merge.

I was thinking about what more we can do with this project.

Should we add like a testimonial section? like a slider to showcase appreciation received for the projects?
I was reading about portfolio websites and it seems they need to have a call to action button like "Hire Me" or something? 

Do open more tasks on the projects if you think these are good ideas. Would be great to hear your ideas as well.
