### ISSUE TITLE
Go to about me section by clicking on the arrow on the home page, and not to the skills section

### ISSUE THREAD

**Issue by thalytabdn** [thalytabdn/Portfolio#17]

**Comment by mkamranhamid** [comment]
Hey, I would like to work on this. Just to confirm you want the route to about me page on clicking on the skills section, correct?

**Comment by thalytabdn** [comment]
I want to go to about me on clicking in the arrow, not in the skills section. Now its going to the skills sections, i dont want this.

**Comment by mkamranhamid** [comment]
cool. let me have it

**Comment by mkamranhamid** [comment]
Done
