### ISSUE TITLE
Issue when opened in mobile

### ISSUE THREAD

**Issue by AdityaNikhil** [thalytabdn/Portfolio#22]
Hi there,
First of all, this is one of the finest minimalist looking template, and am glad am using it. 
I just like to make one request that, when my website is opened in mobile phone, the **about**, **Skills** , **projects** buttons are overlapped. Can u please fix this as am not much of a web developer.
My website : https://adityanikhil.github.io/main/

**Comment by thalytabdn** [comment]
Hi, thanks for the report. I will fix this
