### ISSUE TITLE
Add CSS :hover Selector

### ISSUE THREAD

**Issue by EugeneGohh** [thalytabdn/Portfolio#23]
* Suggesting to add (CSS :hover Selector), when a user hover over it, color appear on it.

![addhover](https://user-images.githubusercontent.com/64187129/99926023-26cb0a00-2d7b-11eb-89f1-a8e352d3da41.png)

**Comment by ghost** [comment]
I want to work on this issue. please assign me.

**Comment by ghost** [comment]
which color u want.Any specific choice

**Comment by AdityaNikhil** [comment]
@shahbazalam07  I suggest, just add a border around the button when hovered. It'd be good if the border colour matches the below image colour,
https://github.com/thalytabdn/Portfolio/blob/master/assets/about-me.png

**Comment by ghost** [comment]
I already done PR

**Comment by thalytabdn** [comment]
this button had a border, but I removed it because it was giving a responsive problem when opened on mobile. I suggest just make a zoom when hovered

**Comment by AdityaNikhil** [comment]
@thalytabdn  How about zoom with colour filled on the button?! 
Especially this colour,
https://github.com/thalytabdn/Portfolio/blob/master/assets/about-me.png

**Comment by thalytabdn** [comment]
Change just the text color, without border
